version: "3.9"

services:
  fastapi:
    container_name: fastapi-server
    build:
      context: .
      dockerfile: Dockerfile.api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  webhook-bot:
    container_name: cloudmiuyaka-wh
    build:
      context: .
      dockerfile: Dockerfile.bot
    command: python bot.py
    env_file:
      - .env
    depends_on:
      - fastapi
    restart: unless-stopped
